import { Issue, User, ActionItem } from "@/types/issue";

export const mockUsers: User[] = [
  { id: "1", name: "John Smith", email: "john.smith@company.com", department: "IT" },
  { id: "2", name: "Sarah Johnson", email: "sarah.johnson@company.com", department: "Finance" },
  { id: "3", name: "Michael Brown", email: "michael.brown@company.com", department: "Operations" },
  { id: "4", name: "Emily Davis", email: "emily.davis@company.com", department: "HR" },
  { id: "5", name: "David Wilson", email: "david.wilson@company.com", department: "Legal" },
];

export const mockIssues: Issue[] = [
  {
    id: 2001,
    title: "Security patch deployment delayed",
    summary: "Critical security patches for customer-facing applications are delayed due to resource constraints.",
    owner: mockUsers[0],
    affectedFunction: "IT",
    status: "In Progress",
    dateOfOccurrence: new Date("2025-09-25"),
    dateOfDiscovery: new Date("2025-09-26"),
    dueDate: new Date("2025-10-10"),
    issueSource: "Internal Audit",
    severityClassification: "High",
    impactTypes: ["Operational", "Regulatory"],
    riskLevel1: "Cyber Security",
    riskLevel2: "Network Security",
    riskLevel3: "Firewall",
    observers: [mockUsers[4]],
    createdAt: new Date("2025-09-26"),
    updatedAt: new Date("2025-09-30"),
  },
  {
    id: 2002,
    title: "Vendor invoice reconciliation discrepancy",
    summary: "Monthly vendor invoices show discrepancies that need investigation and resolution.",
    owner: mockUsers[1],
    affectedFunction: "Finance",
    status: "Completed",
    dateOfOccurrence: new Date("2025-09-20"),
    dateOfDiscovery: new Date("2025-09-22"),
    dueDate: new Date("2025-10-05"),
    issueSource: "Management Review",
    severityClassification: "Medium",
    impactTypes: ["Financial"],
    riskLevel1: "Financial Reporting",
    riskLevel2: "Accuracy",
    riskLevel3: "Management Reports",
    observers: [mockUsers[2]],
    linkedIncidents: [1002],
    createdAt: new Date("2025-09-22"),
    updatedAt: new Date("2025-09-29"),
  },
  {
    id: 2003,
    title: "Employee training compliance gap",
    summary: "Several employees have not completed mandatory compliance training by the deadline.",
    owner: mockUsers[3],
    affectedFunction: "HR",
    status: "Submitted",
    dateOfOccurrence: new Date("2025-09-28"),
    dateOfDiscovery: new Date("2025-09-28"),
    dueDate: new Date("2025-10-15"),
    issueSource: "Self-Identified",
    severityClassification: "Medium",
    impactTypes: ["Regulatory", "Operational"],
    riskLevel1: "Compliance",
    riskLevel2: "Internal Policies",
    riskLevel3: "HR Policies",
    observers: [mockUsers[0]],
    createdAt: new Date("2025-09-28"),
    updatedAt: new Date("2025-09-28"),
  },
  {
    id: 2004,
    title: "Data backup verification failure",
    summary: "Automated backup verification tests failed for critical systems.",
    owner: mockUsers[0],
    affectedFunction: "IT",
    status: "In Progress",
    dateOfOccurrence: new Date("2025-09-27"),
    dateOfDiscovery: new Date("2025-09-27"),
    dueDate: new Date("2025-10-08"),
    issueSource: "System Alert",
    severityClassification: "Critical",
    impactTypes: ["Operational"],
    riskLevel1: "Technology",
    riskLevel2: "Infrastructure",
    riskLevel3: "Servers",
    observers: [mockUsers[2]],
    extensionStatus: "Open",
    createdAt: new Date("2025-09-27"),
    updatedAt: new Date("2025-09-30"),
  },
  {
    id: 2005,
    title: "Contract renewal documentation missing",
    summary: "Key vendor contract renewal documentation cannot be located in the system.",
    owner: mockUsers[4],
    affectedFunction: "Legal",
    status: "Draft",
    dateOfOccurrence: new Date("2025-09-30"),
    dateOfDiscovery: new Date("2025-09-30"),
    dueDate: new Date("2025-10-20"),
    issueSource: "Self-Identified",
    severityClassification: "Low",
    impactTypes: ["Operational"],
    riskLevel1: "Third Party",
    riskLevel2: "Vendor Management",
    riskLevel3: "Contract Disputes",
    observers: [],
    createdAt: new Date("2025-09-30"),
    updatedAt: new Date("2025-09-30"),
  },
  {
    id: 2006,
    title: "API rate limit threshold exceeded",
    summary: "Third-party API rate limits repeatedly exceeded causing service degradation.",
    owner: mockUsers[2],
    affectedFunction: "Operations",
    status: "Closed",
    dateOfOccurrence: new Date("2025-09-18"),
    dateOfDiscovery: new Date("2025-09-19"),
    dueDate: new Date("2025-09-30"),
    issueSource: "External Report",
    severityClassification: "Medium",
    impactTypes: ["Operational"],
    riskLevel1: "Technology",
    riskLevel2: "Applications",
    riskLevel3: "Web Applications",
    observers: [mockUsers[0]],
    createdAt: new Date("2025-09-19"),
    updatedAt: new Date("2025-09-29"),
  },
];

export const issueSources = [
  "Internal Audit",
  "External Audit",
  "Management Review",
  "Self-Identified",
  "Customer Complaint",
  "Regulatory Review",
  "System Alert",
  "External Report",
];

export const businessFunctions = [
  "IT",
  "Finance",
  "Operations",
  "HR",
  "Legal",
  "Marketing",
  "Sales",
];

export const riskCategories = {
  level1: [
    "Cyber Security",
    "Technology",
    "Compliance",
    "Third Party",
    "Internal Controls",
    "Financial Reporting",
  ],
  level2: {
    "Cyber Security": ["Data Protection", "Network Security", "Access Control"],
    "Technology": ["Infrastructure", "Applications", "Cloud Services"],
    "Compliance": ["Data Privacy", "Industry Regulations", "Internal Policies"],
    "Third Party": ["Vendor Management", "Partner Relations", "Supplier Quality"],
    "Internal Controls": ["Access Management", "Audit", "Process Controls"],
    "Financial Reporting": ["Accuracy", "Timeliness", "Disclosure"],
  },
  level3: {
    "Data Protection": ["Customer Data", "Employee Data", "Sensitive Information"],
    "Network Security": ["Firewall", "Intrusion Detection", "VPN"],
    "Access Control": ["Authentication", "Authorization", "Privilege Management"],
    "Infrastructure": ["Servers", "Payment Systems", "Network Equipment"],
    "Applications": ["Business Applications", "Web Applications", "Mobile Apps"],
    "Cloud Services": ["SaaS", "IaaS", "PaaS"],
    "Data Privacy": ["GDPR", "CCPA", "Data Retention"],
    "Industry Regulations": ["SOX", "HIPAA", "PCI-DSS"],
    "Internal Policies": ["Code of Conduct", "Security Policies", "HR Policies"],
    "Vendor Management": ["Contract Disputes", "Performance Issues", "Compliance"],
    "Partner Relations": ["Joint Ventures", "Strategic Partnerships", "Alliances"],
    "Supplier Quality": ["Product Quality", "Delivery", "Certification"],
    "Access Management": ["Role Permissions", "Segregation of Duties", "Monitoring"],
    "Audit": ["Internal Audit", "External Audit", "Compliance Audit"],
    "Process Controls": ["Approval Workflows", "Reconciliation", "Documentation"],
    "Accuracy": ["Quarterly Reports", "Annual Reports", "Management Reports"],
    "Timeliness": ["Filing Deadlines", "Reporting Schedules", "Updates"],
    "Disclosure": ["Material Events", "Related Parties", "Contingencies"],
  },
};

export const mockActionItems: ActionItem[] = [
  {
    id: 3001,
    title: "Apply security patches to all systems",
    owner: mockUsers[0],
    dueDate: new Date("2025-10-08"),
    status: "In Progress",
    description: "Deploy critical security patches across all customer-facing systems",
    comments: "Patches tested in staging environment. Ready for production deployment.",
    linkedIssue: 2001,
    createdAt: new Date("2025-09-26"),
    updatedAt: new Date("2025-09-30"),
  },
  {
    id: 3002,
    title: "Review firewall configuration",
    owner: mockUsers[0],
    dueDate: new Date("2025-10-10"),
    status: "Open",
    description: "Audit and update firewall rules to prevent future issues",
    comments: "Initial review scheduled for next week.",
    linkedIssue: 2001,
    createdAt: new Date("2025-09-26"),
    updatedAt: new Date("2025-09-26"),
  },
  {
    id: 3003,
    title: "Complete backup verification tests",
    owner: mockUsers[0],
    dueDate: new Date("2025-10-06"),
    status: "Open",
    description: "Run comprehensive backup verification for all critical systems",
    linkedIssue: 2004,
    createdAt: new Date("2025-09-27"),
    updatedAt: new Date("2025-09-27"),
  },
  {
    id: 3004,
    title: "Update backup monitoring procedures",
    owner: mockUsers[0],
    dueDate: new Date("2025-10-08"),
    status: "Open",
    description: "Enhance automated monitoring and alerting for backup systems",
    linkedIssue: 2004,
    createdAt: new Date("2025-09-27"),
    updatedAt: new Date("2025-09-27"),
  },
];
