import { Incident, User } from "@/types/incident";

export const mockUsers: User[] = [
  { id: "1", name: "John Smith", email: "john.smith@company.com", department: "IT" },
  { id: "2", name: "Sarah Johnson", email: "sarah.johnson@company.com", department: "Finance" },
  { id: "3", name: "Michael Brown", email: "michael.brown@company.com", department: "Operations" },
  { id: "4", name: "Emily Davis", email: "emily.davis@company.com", department: "HR" },
  { id: "5", name: "David Wilson", email: "david.wilson@company.com", department: "Legal" },
];

export const mockIncidents: Incident[] = [
  {
    id: 1001,
    title: "Data breach in customer database",
    summary: "Unauthorized access detected in customer database system. Multiple records potentially compromised.",
    owner: mockUsers[0],
    affectedFunction: "IT",
    status: "In Progress",
    dateOfOccurrence: new Date("2025-09-28"),
    dateOfDiscovery: new Date("2025-09-29"),
    incidentType: "Security Breach",
    severityClassification: "Critical",
    impactTypes: ["Financial", "Reputational", "Regulatory"],
    actualFinancialImpact: 50000,
    potentialFinancialImpact: 250000,
    riskLevel1: "Cyber Security",
    riskLevel2: "Data Protection",
    riskLevel3: "Customer Data",
    observers: [mockUsers[1], mockUsers[4]],
    createdAt: new Date("2025-09-29"),
    updatedAt: new Date("2025-09-30"),
  },
  {
    id: 1002,
    title: "System outage - Payment processing",
    summary: "Payment processing system experienced downtime for 3 hours affecting customer transactions.",
    owner: mockUsers[2],
    affectedFunction: "Operations",
    status: "Closed",
    dateOfOccurrence: new Date("2025-09-25"),
    dateOfDiscovery: new Date("2025-09-25"),
    incidentType: "System Failure",
    severityClassification: "High",
    impactTypes: ["Operational", "Financial"],
    actualFinancialImpact: 15000,
    potentialFinancialImpact: 30000,
    riskLevel1: "Technology",
    riskLevel2: "Infrastructure",
    riskLevel3: "Payment Systems",
    observers: [mockUsers[0]],
    justificationForClosure: "System restored, root cause identified and fixed. Monitoring protocols enhanced.",
    createdAt: new Date("2025-09-25"),
    updatedAt: new Date("2025-09-27"),
  },
  {
    id: 1003,
    title: "Compliance violation - GDPR",
    summary: "Customer data retention policy not followed correctly, potential GDPR violation identified.",
    owner: mockUsers[1],
    affectedFunction: "Finance",
    status: "Submitted",
    dateOfOccurrence: new Date("2025-09-20"),
    dateOfDiscovery: new Date("2025-09-27"),
    incidentType: "Compliance",
    severityClassification: "High",
    impactTypes: ["Regulatory", "Reputational"],
    riskLevel1: "Compliance",
    riskLevel2: "Data Privacy",
    riskLevel3: "GDPR",
    observers: [mockUsers[4]],
    createdAt: new Date("2025-09-27"),
    updatedAt: new Date("2025-09-28"),
  },
  {
    id: 1004,
    title: "Vendor contract dispute",
    summary: "Dispute with key vendor regarding service level agreements and deliverables.",
    owner: mockUsers[4],
    affectedFunction: "Legal",
    status: "In Progress",
    dateOfOccurrence: new Date("2025-09-15"),
    dateOfDiscovery: new Date("2025-09-16"),
    incidentType: "Contractual",
    severityClassification: "Medium",
    impactTypes: ["Operational"],
    riskLevel1: "Third Party",
    riskLevel2: "Vendor Management",
    riskLevel3: "Contract Disputes",
    observers: [mockUsers[2]],
    createdAt: new Date("2025-09-16"),
    updatedAt: new Date("2025-09-29"),
  },
  {
    id: 1005,
    title: "Employee data access error",
    summary: "Employee accidentally granted elevated access privileges beyond their role requirements.",
    owner: mockUsers[3],
    affectedFunction: "HR",
    status: "Draft",
    dateOfOccurrence: new Date("2025-09-30"),
    dateOfDiscovery: new Date("2025-09-30"),
    incidentType: "Access Control",
    severityClassification: "Low",
    impactTypes: ["Operational"],
    riskLevel1: "Internal Controls",
    riskLevel2: "Access Management",
    riskLevel3: "Role Permissions",
    observers: [],
    createdAt: new Date("2025-09-30"),
    updatedAt: new Date("2025-09-30"),
  },
  {
    id: 1006,
    title: "Financial reporting discrepancy",
    summary: "Inconsistency found in quarterly financial reports requiring investigation.",
    owner: mockUsers[1],
    affectedFunction: "Finance",
    status: "In Progress",
    dateOfOccurrence: new Date("2025-09-22"),
    dateOfDiscovery: new Date("2025-09-26"),
    incidentType: "Financial",
    severityClassification: "High",
    impactTypes: ["Financial", "Regulatory"],
    actualFinancialImpact: 25000,
    potentialFinancialImpact: 100000,
    riskLevel1: "Financial Reporting",
    riskLevel2: "Accuracy",
    riskLevel3: "Quarterly Reports",
    observers: [mockUsers[0], mockUsers[4]],
    createdAt: new Date("2025-09-26"),
    updatedAt: new Date("2025-09-30"),
  },
];

export const incidentTypes = [
  "Security Breach",
  "System Failure",
  "Compliance",
  "Contractual",
  "Access Control",
  "Financial",
  "Operational",
];

export const businessFunctions = [
  "IT",
  "Finance",
  "Operations",
  "HR",
  "Legal",
  "Marketing",
  "Sales",
];

export const riskCategories = {
  level1: [
    "Cyber Security",
    "Technology",
    "Compliance",
    "Third Party",
    "Internal Controls",
    "Financial Reporting",
  ],
  level2: {
    "Cyber Security": ["Data Protection", "Network Security", "Access Control"],
    "Technology": ["Infrastructure", "Applications", "Cloud Services"],
    "Compliance": ["Data Privacy", "Industry Regulations", "Internal Policies"],
    "Third Party": ["Vendor Management", "Partner Relations", "Supplier Quality"],
    "Internal Controls": ["Access Management", "Audit", "Process Controls"],
    "Financial Reporting": ["Accuracy", "Timeliness", "Disclosure"],
  },
  level3: {
    "Data Protection": ["Customer Data", "Employee Data", "Sensitive Information"],
    "Network Security": ["Firewall", "Intrusion Detection", "VPN"],
    "Access Control": ["Authentication", "Authorization", "Privilege Management"],
    "Infrastructure": ["Servers", "Payment Systems", "Network Equipment"],
    "Applications": ["Business Applications", "Web Applications", "Mobile Apps"],
    "Cloud Services": ["SaaS", "IaaS", "PaaS"],
    "Data Privacy": ["GDPR", "CCPA", "Data Retention"],
    "Industry Regulations": ["SOX", "HIPAA", "PCI-DSS"],
    "Internal Policies": ["Code of Conduct", "Security Policies", "HR Policies"],
    "Vendor Management": ["Contract Disputes", "Performance Issues", "Compliance"],
    "Partner Relations": ["Joint Ventures", "Strategic Partnerships", "Alliances"],
    "Supplier Quality": ["Product Quality", "Delivery", "Certification"],
    "Access Management": ["Role Permissions", "Segregation of Duties", "Monitoring"],
    "Audit": ["Internal Audit", "External Audit", "Compliance Audit"],
    "Process Controls": ["Approval Workflows", "Reconciliation", "Documentation"],
    "Accuracy": ["Quarterly Reports", "Annual Reports", "Management Reports"],
    "Timeliness": ["Filing Deadlines", "Reporting Schedules", "Updates"],
    "Disclosure": ["Material Events", "Related Parties", "Contingencies"],
  },
};
